### ISSUE TITLE
Pull request works but push does not

### ISSUE THREAD

**Issue by frenzymadness** [fedora-python/tox-github-action#7]
I've tried to experimentally configure this action for my fork of micropipenv — [PR with the GH actions config](https://github.com/frenzymadness/micropipenv/pull/1)

Pull request event works well but push event seems to don't mount the project folder correctly because tox complains about missing configuration.

Feel free to close this issue if the result I have is expected for the first PR with GH action config.

**Comment by encukou** [comment]
For the push event, the [tested code](https://github.com/frenzymadness/micropipenv/pull/1/checks#step:3:336) was commit https://github.com/frenzymadness/micropipenv/pull/1/commits/e72617b725b76dfd48c6ac1af1af24282a1f6606 -- exactly the one pushed to the `gh_actions` branch from which the PR was made. Note that it [does not have tox.ini](https://github.com/frenzymadness/micropipenv/tree/e72617b725b76dfd48c6ac1af1af24282a1f6606)
The test failed because in the `gh_actions`, on its own, tox does fail.

For the pull request test, the `gh_actions` branch [was merged to `master`](https://github.com/frenzymadness/micropipenv/pull/1/checks?check_run_id=729852790#step:3:367), which does have tox.ini.

I recommend testing "push" only on "production" branches. For feature branches that should be merged, "pull request" should be enough.

**Comment by frenzymadness** [comment]
Thank you, that makes perfect sense. I've enabled all the branches so I can test it and I don't have to merge it to master.
